### ISSUE TITLE
How does one customize the Zendesk subdomain?

### ISSUE THREAD

**Issue by steveamaza** [raamdev/alfred-zendesk-search#1]
Hi @raamdev, brilliant workflow. However, when I installed and tried to search for `zd 253824`, it opened up https://wordpressvip.zendesk.com/agent/tickets/253824.

How do I configure this to work with paystack.zendesk.com?

**Comment by raamdev** [comment]
@steveamaza Thanks for the question! I've updated the workflow and published [a new release](https://github.com/raamdev/alfred-zendesk-search/releases/tag/v1.0) that lets you configure Alfred workflow variables for your specific Zendesk instance. I've also included instructions here: https://github.com/raamdev/alfred-zendesk-search#initial-configuration

If you have any other questions, or if you run into any trouble with the above, please let me know.
